[tool.poetry]
name = "docker-compose-python-backend"
version = "2020.6"
description = "Backend API for boilerplate application with Sanic and React."
authors = ["yoziru"]
repository = "https://github.com/yoziru/docker-compose-python-node-react"

[tool.poetry.dependencies]
python = "^3.7"
sanic = "^20.6.3"
asyncpg = "^0.20.1"
sanic-cors = "^0.10.0"
secure = "^0.2.1"
orjson = "^3.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
flake8 = "^3.8.3"
isort = "^4.3.21"
black = "^19.10b0"
importlib_metadata = "^1.7.0"

[tool.black]
line-length = 88
target-version = ['py36']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
